# Generated by Django 4.0.5 on 2022-06-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_adddress_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adddress',
            new_name='address',
        ),
    ]
